### ISSUE TITLE
CMD: config command doesn’t handle spaces within strings well

### ISSUE THREAD

**Issue by genesisdotnet** [genesisdotnet/genesis#8]
If you’re setting a config value that has something like 
`config mssql ConnectionString=“the string”`

When you show the config for mssql it stops off at the space. 

The value ends up “the”, and not “the string”

**Comment by solatticus** [comment]
script:
-----
add mssql
config mssql ConnectionString="Something with spaces"
config mssql
-----
Dumps out the expected string, spaces included... old bug.
